Proj/urls.py
from django.urls import path
from . import views


app_name = 'proj'
urlpatterns = [

    #Main
    path('login/', views.Login.as_view(), name='login'),
    path('', views.Main.as_view(), name='main'),
    path('join/', views.Join.as_view(), name='join'),
    path('edit/', views.Edit.as_view(), name='edit'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('admin/', views.Admin.as_view(), name='admin'),
    path('<str:name>/maps/', views.Maps.as_view(), name='maps'),
    path('payment/', views.Payment, name='payment'),
    path('refund/', views.Refund, name='refund'),   
    path('pclist/', views.Pclist, name='pclist'), 
    path('setting/', views.Setting.as_view(), name='setting'),
    path('food/', views.Food.as_view(), name='food'),    


     
    #Board
    path('board/', views.Boarding.as_view(), name='board'),
    path('board/manage/', views.BoardManage.as_view(), name='boardmanage'),
    path('board/<int:boardnum>/', views.ContentList.as_view(), name='contentlist'),
    path('board/<int:boardnum>/search/', views.SearchContent.as_view(), name='searchcontent'),
    path('board/<int:boardnum>/<int:textnum>/', views.Content.as_view(), name='content'),
    path('board/write/', views.Write.as_view(), name='write'),
    path('board/<int:boardnum>/<int:textnum>/delete/', views.Delete.as_view(), name='delete'),


    #maps
    path('fox/', views.Fox, name='fox'),
    path('ghostcastle/', views.Ghostcastle, name='ghostcastle'),
    path('lime/', views.Lime, name='lime'),
    path('pop/', views.Pop, name='pop'),
    path('skybridge/', views.Skybridge, name='skybridge'),
    path('ocelot/', views.Ocelot, name='ocelot'),
   
]

TermProj/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Proj.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proj/models.py
from django.db import models
from taggit.managers import TaggableManager


class User(models.Model):
    my_id = models.CharField(max_length=100, default='admin', primary_key=True)
    pw = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    ph = models.IntegerField(default=0)
    time = models.IntegerField(default=0)
    sex = models.IntegerField(default=0)
    region = models.IntegerField(default=0)
    avg_time = models.IntegerField(default=0)
    food_choice = models.IntegerField(default=0)
    age = models.IntegerField(default=20)

    
    def __str__(self):
        return self.my_id

class Board(models.Model):
    boardnum = models.IntegerField(default=0, primary_key=True)
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title


class Text(models.Model):
    boardnumber = models.ForeignKey('Board', null=True, blank=True, on_delete=models.CASCADE)
    text_title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    star = models.IntegerField(default=0)
    tags = TaggableManager(blank=True)
    user = models.CharField(max_length=100, default='default')

    def __str__(self):
        return self.text_title

Proj/forms.py
from django import forms
from Proj.models import *


class JoinForm(forms.Form):
    your_id = forms.EmailField(label='아이디', max_length=100)
    your_pw = forms.CharField(label='비밀번호', max_length=100, widget = forms.PasswordInput)
    your_ph = forms.IntegerField(label='전화번호(숫자만)')
    your_name = forms.CharField(label='이름', max_length=10)
    your_age = forms.IntegerField(label='나이')
    your_sex = forms.IntegerField(label='성별(안내문 참조)')
    your_avg_time = forms.IntegerField(label='하루 평균 PC방 이용시간(안내문 참조)')
    your_food_choice = forms.IntegerField(label='음식 주문 여부(안내문 참조)')

class LoginForm(forms.Form):
    your_id = forms.EmailField(label='아이디', max_length=100)
    your_pw = forms.CharField(label='비밀번호', max_length=100, widget = forms.PasswordInput)

class AdminForm(forms.Form):
    your_id = forms.EmailField(label='학생 ID', max_length=100)

class EditForm(forms.Form):
    your_pw = forms.CharField(label='비밀번호', max_length=100, widget = forms.PasswordInput)
    your_ph = forms.CharField(label='전화번호', max_length=11)
    your_name = forms.CharField(label='이름', max_length=10)

class BoardForm(forms.Form):
    your_board = forms.ChoiceField(widget = forms.Select(), choices = ([('1','리뷰 게시판')]), initial='1', label='게시판 선택', required = True)
    your_title = forms.CharField(max_length=200, label='제목')
    your_content = forms.CharField(widget=forms.Textarea, label='내용')
    your_star = forms.ChoiceField(widget = forms.Select(), choices = ([('1','★'), ('2','★★'),('3','★★★'), ('4','★★★★'), ('5','★★★★★')]), initial='1', label='별점 선택', required = True)
    your_tag = forms.CharField(max_length=200, label='태그', required=False, widget=forms.TextInput(attrs={'placeholder': 'comma-separated'}))

class NoticeForm(forms.Form):
    your_board = forms.ChoiceField(widget = forms.Select(), choices = ([('1','리뷰 게시판'), ('2','공지사항')]), initial='1', label='게시판 선택', required = True)
    your_title = forms.CharField(max_length=200, label='제목')
    your_content = forms.CharField(widget=forms.Textarea, label='내용')

class BoardManageForm(forms.Form):
    your_boardnum = forms.IntegerField(label='게시판번호')
    your_board = forms.CharField(label='게시판명', max_length=100)

class SearchForm(forms.Form):
    your_search = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'placeholder': 'Enter HashTags..'}))

class SettingForm(forms.Form):
    your_settingnum = forms.IntegerField(label='시간설정')

class FoodForm(forms.Form):
    your_con1 = forms.ChoiceField(widget = forms.Select(), choices = ([('0','갈비만두'), ('1','감자튀김'),('2','떡볶이'), ('3','레몬에이드'), ('4','불닭볶음면'), ('5','소떡소떡'), ('6','수제소시지'), ('7','스프라이트'), ('8','슬라이스 치즈'), ('9','신라면'), ('10','아메리카노'), ('11','자몽에이드'), ('12','제육덮밥'), ('13','짜파게티'), ('14','참치김밥'), ('15','청포도에이드'), ('16','치킨마요덮밥'), ('17','코카콜라'), ('18','펩시'), ('19','포스틱'), ('20','포카칩'), ('21','핫도그'), ('22','핫바'), ('23','햇반'), ('24','허니버터칩'), ('25','홈런볼')]), initial='0', label='메뉴 선택', required = True)

Proj/views.py
from django.views.generic import ListView, FormView
from django.views import View
from Proj.models import *
from taggit.models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from Proj.forms import *
import json
import hashlib
from django.db.models import Q
import joblib
import pandas as pd


class Login(FormView):
    form_class = LoginForm
    template_name ="Proj/login.html"

    def get(self,request,*args,**kwargs):
        form = self.form_class(initial= self.initial)
        #request.session['login'] = False # 추가 session
        return render(request,self.template_name,{'form':form})

    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_id = form.cleaned_data['your_id']
            new_pw = form.cleaned_data['your_pw']
            m = hashlib.sha256()
            m.update(new_pw.encode('UTF-8'))
            x = m.hexdigest()
            
            try:
                 data = User.objects.get(my_id=new_id)
            except Exception:
                return redirect('proj:login')

            if x == data.pw:
                request.session['login'] = True # 추가 로그인 성공시 True 설정
                request.session['my_id'] = data.my_id
                request.session['time'] = data.time
                request.session['name'] = data.name

                return redirect('proj:main')
            else:
                return redirect('proj:login')
        
        return render(request,self.template_name,{'form':form})
    

class Main(View):

    def get(self, request, *args, **kwargs):
        #if not request.session.get('login', False):
        #    return HttpResponseRedirect('/')
        
        userdata = request.session.get('my_id')
        context = {'model_list':['Board'], 'userdata':userdata}

        return render(request, 'Proj/main.html', context=context)

class Join(FormView):
    form_class = JoinForm
    template_name ="Proj/join.html"

    def get(self,request,*args,**kwargs):
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

    def post(self,request,*args,**kwargs):                  #my_id, pw, name, number, prof
        form = self.form_class(request.POST)
        if form.is_valid():
            new_id = form.cleaned_data['your_id']
            new_pw = form.cleaned_data['your_pw']
            new_ph = form.cleaned_data['your_ph']
            new_name = form.cleaned_data['your_name']
            new_sex = form.cleaned_data['your_sex']
            new_age = form.cleaned_data['your_age']
            new_avg_time = form.cleaned_data['your_avg_time']
            new_food_choice = form.cleaned_data['your_food_choice']
            m = hashlib.sha256()
            m.update(new_pw.encode('UTF-8'))
            x = m.hexdigest()
            try:
                User.objects.create(my_id=new_id, pw=x, name=new_name, ph=new_ph, sex = new_sex, region = 6., avg_time = new_avg_time, food_choice=new_food_choice, age=new_age)
            except:
                return redirect('proj:join')
            request.session['login'] = False
            return HttpResponseRedirect('/')
        
        return render(request,self.template_name,{'form':form})


class Edit(FormView):
    form_class = EditForm
    template_name = 'Proj/edit.html'

    def get(self,request,*args,**kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        new_my_id = request.session.get('my_id')
        form = self.form_class(initial= {'your_id':new_my_id})

        return render(request,self.template_name,{'form':form, 'my_id':new_my_id}) #, 'new_id':new_id
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_my_id = request.session.get('my_id')
            new_pw = form.cleaned_data['your_pw']
            new_ph = form.cleaned_data['your_ph']
            new_name = form.cleaned_data['your_name']
            try:
                data = User.objects.get(my_id=new_my_id)
            except Exception:
                return HttpResponse(Exception)

            m = hashlib.sha256()
            m.update(new_pw.encode('UTF-8'))
            x = m.hexdigest()
            if new_name != data.name or new_ph != data.ph or x != data.pw:
                data.pw=x
                data.ph=new_ph
                data.name=new_name
                data.save()
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/edit/')
        request.session['login'] = False

        return render(request,self.template_name,{'form':form})        


class Logout(View):

    def get(self, request, *args, **kwargs):
        request.session['login'] = False
        request.session['my_id'] = {}
        request.session['name'] = {}
        request.session['time'] = {}
        return HttpResponseRedirect('/')


class Admin(FormView):
    form_class = AdminForm
    template_name = 'Proj/admin.html'

    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_id = form.cleaned_data['your_id']
            new_prof = form.cleaned_data['your_prof']
            try:
                post_instance = User.objects.filter(my_id=new_id)
                post_instance.update(prof=new_prof)
            except Exception:
                return render(request, 'Proj/admin.html', {'form':form})

            return HttpResponseRedirect('/admin/')

        return render(request, 'Proj/admin.html', {'form':form})

class Maps(View):
    
    def get(self, request, name):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        pcname = name
        return render(request, 'Proj/maps.html', {'name':pcname})           

class Setting(FormView):
    form_class = SettingForm
    template_name = 'Proj/main.html'
    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = SettingForm
        return render(request, 'Proj/setting.html' ,{'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)    
        if form.is_valid():
            new_boardnum = form.cleaned_data['your_settingnum']
            time = new_boardnum
            return render(request, self.template_name ,{'form':form})

class Distance(View):
    
    def get(self, request):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        
        return render(request, 'Proj/distance.html')  

class Boarding(View):
    
    def get(self, request):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')

        val = request.session.get('my_id')
        userdata = User.objects.get(my_id = val)
        boarddata1 = Board.objects.all()

        return render(request, 'proj/board.html', {'userdata':userdata, 'boarddata':boarddata1})


class BoardManage(FormView):
    form_class = BoardManageForm
    template_name = 'Proj/boardmanage.html'
    
    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_boardnum = form.cleaned_data['your_boardnum']
            new_board = form.cleaned_data['your_board']
            Board.objects.create(boardnum=new_boardnum, title=new_board)                

        return redirect('proj:main')

class ContentList(View):

    def get(self, request, boardnum):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')

        data = Text.objects.filter(boardnumber=boardnum).order_by('-id')
        form = SearchForm
        bn = boardnum
        return render(request, 'proj/contentlist.html', {'data':data, 'bn':bn, 'form':form})

    def post(self, request, boardnum):
    
        data = Text.objects.filter(boardnumber=boardnum).order_by('-star')
        bn = boardnum
        form = SearchForm
        return render(request, 'proj/contentlist.html', {'data':data, 'bn':bn, 'form':form})


class SearchContent(FormView):
    form_class = SearchForm
    template_name = 'Proj/contentlist.html'
    
    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

    def post(self, request, boardnum):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_search = form.cleaned_data['your_search']
            data = Text.objects.filter(boardnumber=boardnum).filter(tags__name=new_search)
            bn = boardnum
            return render(request, 'Proj/contentlist.html', {'data':data, 'bn':bn, 'form':form})

        return redirect('proj:main')


class Food(FormView):
    form_class = FoodForm
    template_name = 'Proj/food.html'

    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

Proj/templates/pc/fox.html
{% extends "Proj/main.html" %}
{% block content %}
<script src="https://code.jquery.com/jquery-latest.js"></script> 
 
    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 0; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: hidden; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }
    
        /* Modal Content/Box */
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 30%; /* Could be more or less, depending on screen size */                          
        }
 
</style>
    <!-- The Modal -->
    <div id="myModal1" class="modal">
        
      <!-- Modal content -->
      <div class="modal-content">
          
                <p style="text-align: center;"><span style="font-size: 14pt;"><b><span style="font-size: 20pt;">팍스 PC방</span></b></span></p>
                <p style="text-align: center; line-height: 1.0;"><br /></p>
                <p style="text-align: center; line-height: 1.5;"><b><span style="font-size: 14pt;">PC 사양</span></b></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">CPU : i5-9600K</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">VGA : RTX 2070</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">RAM : 16GB</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">MONITOR : 삼성 43인치 UHD TV UN43KU7000 </span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">회원정액제</span></p>
                <div style="text-align: center;">
                <img src="/media/pop.jpg" width="150" height="150"></div>
                <a href="{% url 'proj:maps' name1 %}">pc방 위치</a>
                <p><br /></p>
            <!-- <div style="cursor:pointer;background-color:#DDDDDD;text-align: center;padding-bottom: 10px;padding-top: 10px;" onClick="close_pop();">
                <span class="pop_bt" style="font-size: 14pt;" >
                     닫기
                </span>
                
            </div> -->
      </div>
 
    </div>
        <!--End Modal-->
       
    <script type="text/javascript">
      
        jQuery(document).ready(function() {
                $('#myModal1').show();
        });
        //팝업 Close 기능
        function close_pop(flag) {
             $('#myModal1').hide();
        };
        
      </script>
      
{% endblock %}

Proj/templates/pc/ghostcastle.html
{% extends "Proj/main.html" %}
{% block content %}
<script src="https://code.jquery.com/jquery-latest.js"></script> 
 
    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 0; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: hidden; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }
    
        /* Modal Content/Box */
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 30%; /* Could be more or less, depending on screen size */                          
        }
 
</style>
    <!-- The Modal -->
    <div id="myModal2" class="modal">
        
      <!-- Modal content -->
      <div class="modal-content">
          
                <p style="text-align: center;"><span style="font-size: 14pt;"><b><span style="font-size: 20pt;">고스트캐슬 PC방</span></b></span></p>
                <p style="text-align: center; line-height: 1.0;"><br /></p>
                <p style="text-align: center; line-height: 1.5;"><b><span style="font-size: 14pt;">PC 사양</span></b></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">CPU : i5-4690</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">VGA : RTX 2060</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">RAM : 16GB</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">MONITOR : Benq 2720(144hz) </span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">회원정액제</span></p>
                <div style="text-align: center;">
                <img src="/media/pop.jpg" width="150" height="150"></div>
                <a href="{% url 'proj:maps' name2 %}">pc방 위치</a>
                <p><br /></p>
            <!-- <div style="cursor:pointer;background-color:#DDDDDD;text-align: center;padding-bottom: 10px;padding-top: 10px;" onClick="close_pop();">
                <span class="pop_bt" style="font-size: 14pt;" >
                     닫기
                </span>
                
            </div> -->
      </div>
 
    </div>
        <!--End Modal-->
       
    <script type="text/javascript">
      
        jQuery(document).ready(function() {
                $('#myModal2').show();
        });
        //팝업 Close 기능
        function close_pop(flag) {
             $('#myModal2').hide();
        };
        
      </script>
      
{% endblock %}

Proj/templates/pc/lime.html
{% extends "Proj/main.html" %}
{% block content %}
<script src="https://code.jquery.com/jquery-latest.js"></script> 
 
    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 0; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: hidden; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }
    
        /* Modal Content/Box */
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 30%; /* Could be more or less, depending on screen size */                          
        }
 
</style>
    <!-- The Modal -->
    <div id="myModal3" class="modal">
        
      <!-- Modal content -->
      <div class="modal-content">
          
                <p style="text-align: center;"><span style="font-size: 14pt;"><b><span style="font-size: 20pt;">라임 PC방</span></b></span></p>
                <p style="text-align: center; line-height: 1.0;"><br /></p>
                <p style="text-align: center; line-height: 1.5;"><b><span style="font-size: 14pt;">PC 사양</span></b></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">CPU : i5-4690</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">VGA : GTX 1080</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">RAM : 32GB</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">MONITOR : 21:9 200Hz/165Hz</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">회원정액제</span></p>
                <div style="text-align: center;">
                <img src="/media/pop.jpg" width="150" height="150"></div>
                <a href="{% url 'proj:maps' name3 %}">pc방 위치</a>
                <p><br /></p>
            <!-- <div style="cursor:pointer;background-color:#DDDDDD;text-align: center;padding-bottom: 10px;padding-top: 10px;" onClick="close_pop();">
                <span class="pop_bt" style="font-size: 14pt;" >
                     닫기
                </span>
                
            </div> -->
      </div>
 
    </div>
        <!--End Modal-->
       
    <script type="text/javascript">
      
        jQuery(document).ready(function() {
                $('#myModal3').show();
        });
        //팝업 Close 기능
        function close_pop(flag) {
             $('#myModal3').hide();
        };
        
      </script>
      
{% endblock %}

Proj/templates/pc/ocelot.html
{% extends "Proj/main.html" %}
{% block content %}
<script src="https://code.jquery.com/jquery-latest.js"></script> 
 
    <style>
        /* The Modal (background) */
        .modal {
            display: none; /* Hidden by default */
            position: fixed; /* Stay in place */
            z-index: 0; /* Sit on top */
            left: 0;
            top: 0;
            width: 100%; /* Full width */
            height: 100%; /* Full height */
            overflow: hidden; /* Enable scroll if needed */
            background-color: rgb(0,0,0); /* Fallback color */
            background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
        }
    
        /* Modal Content/Box */
        .modal-content {
            background-color: #fefefe;
            margin: 5% auto; /* 15% from the top and centered */
            padding: 20px;
            border: 1px solid #888;
            width: 30%; /* Could be more or less, depending on screen size */                          
        }
 
</style>
    <!-- The Modal -->
    <div id="myModal4" class="modal">
        
      <!-- Modal content -->
      <div class="modal-content">
          
                <p style="text-align: center;"><span style="font-size: 14pt;"><b><span style="font-size: 20pt;">오셀롯 PC방</span></b></span></p>
                <p style="text-align: center; line-height: 1.0;"><br /></p>
                <p style="text-align: center; line-height: 1.5;"><b><span style="font-size: 14pt;">PC 사양</span></b></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">CPU : i7-8400</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">VGA : GTX 1080</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">RAM : 32GB</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">MONITOR : 게이밍 165Hz 배그 모니터</span></p>
                <p style="text-align: center; line-height: 1.5;"><span style="font-size: 14pt;">회원정액제</span></p>
                <div style="text-align: center;">
                <img src="/media/pop.jpg" width="150" height="150"></div>
                <a href="{% url 'proj:maps' name4 %}">pc방 위치</a>
                <p><br /></p>
            <!-- <div style="cursor:pointer;background-color:#DDDDDD;text-align: center;padding-bottom: 10px;padding-top: 10px;" onClick="close_pop();">
                <span class="pop_bt" style="font-size: 14pt;" >
                     닫기
                </span>
                
            </div> -->
      </div>
 
    </div>
        <!--End Modal-->
       
    <script type="text/javascript">
      
        jQuery(document).ready(function() {
                $('#myModal4').show();
        });
        //팝업 Close 기능
        function close_pop(flag) {
             $('#myModal4').hide();
        };
        
      </script>
      
{% endblock %}