Proj/urls.py
from django.urls import path
from . import views


app_name = 'proj'
urlpatterns = [

    #Main
    path('login/', views.Login.as_view(), name='login'),
    path('', views.Main.as_view(), name='main'),
    path('join/', views.Join.as_view(), name='join'),
    path('edit/', views.Edit.as_view(), name='edit'),
    path('logout/', views.Logout.as_view(), name='logout'),
    path('admin/', views.Admin.as_view(), name='admin'),
    path('<str:name>/maps/', views.Maps.as_view(), name='maps'),
    path('payment/', views.Payment, name='payment'),
    path('refund/', views.Refund, name='refund'),   
    path('pclist/', views.Pclist, name='pclist'), 
    path('setting/', views.Setting.as_view(), name='setting'),
    path('food/', views.Food.as_view(), name='food'),    


     
    #Board
    path('board/', views.Boarding.as_view(), name='board'),
    path('board/manage/', views.BoardManage.as_view(), name='boardmanage'),
    path('board/<int:boardnum>/', views.ContentList.as_view(), name='contentlist'),
    path('board/<int:boardnum>/search/', views.SearchContent.as_view(), name='searchcontent'),
    path('board/<int:boardnum>/<int:textnum>/', views.Content.as_view(), name='content'),
    path('board/write/', views.Write.as_view(), name='write'),
    path('board/<int:boardnum>/<int:textnum>/delete/', views.Delete.as_view(), name='delete'),


    #maps
    path('fox/', views.Fox, name='fox'),
    path('ghostcastle/', views.Ghostcastle, name='ghostcastle'),
    path('lime/', views.Lime, name='lime'),
    path('pop/', views.Pop, name='pop'),
    path('skybridge/', views.Skybridge, name='skybridge'),
    path('ocelot/', views.Ocelot, name='ocelot'),
   
]

TermProj/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('Proj.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Proj/models.py
from django.db import models
from taggit.managers import TaggableManager


class User(models.Model):
    my_id = models.CharField(max_length=100, default='admin', primary_key=True)
    pw = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    ph = models.IntegerField(default=0)
    time = models.IntegerField(default=0)
    sex = models.IntegerField(default=0)
    region = models.IntegerField(default=0)
    avg_time = models.IntegerField(default=0)
    food_choice = models.IntegerField(default=0)
    age = models.IntegerField(default=20)

    
    def __str__(self):
        return self.my_id

class Board(models.Model):
    boardnum = models.IntegerField(default=0, primary_key=True)
    title = models.CharField(max_length=100)
    
    def __str__(self):
        return self.title


class Text(models.Model):
    boardnumber = models.ForeignKey('Board', null=True, blank=True, on_delete=models.CASCADE)
    text_title = models.CharField(max_length=100)
    content = models.CharField(max_length=100)
    star = models.IntegerField(default=0)
    tags = TaggableManager(blank=True)
    user = models.CharField(max_length=100, default='default')

    def __str__(self):
        return self.text_title

Proj/forms.py
from django import forms
from Proj.models import *


class JoinForm(forms.Form):
    your_id = forms.EmailField(label='아이디', max_length=100)
    your_pw = forms.CharField(label='비밀번호', max_length=100, widget = forms.PasswordInput)
    your_ph = forms.IntegerField(label='전화번호(숫자만)')
    your_name = forms.CharField(label='이름', max_length=10)
    your_age = forms.IntegerField(label='나이')
    your_sex = forms.IntegerField(label='성별(안내문 참조)')
    your_avg_time = forms.IntegerField(label='하루 평균 PC방 이용시간(안내문 참조)')
    your_food_choice = forms.IntegerField(label='음식 주문 여부(안내문 참조)')

class LoginForm(forms.Form):
    your_id = forms.EmailField(label='아이디', max_length=100)
    your_pw = forms.CharField(label='비밀번호', max_length=100, widget = forms.PasswordInput)

class AdminForm(forms.Form):
    your_id = forms.EmailField(label='학생 ID', max_length=100)

class EditForm(forms.Form):
    your_pw = forms.CharField(label='비밀번호', max_length=100, widget = forms.PasswordInput)
    your_ph = forms.CharField(label='전화번호', max_length=11)
    your_name = forms.CharField(label='이름', max_length=10)

class BoardForm(forms.Form):
    your_board = forms.ChoiceField(widget = forms.Select(), choices = ([('1','리뷰 게시판')]), initial='1', label='게시판 선택', required = True)
    your_title = forms.CharField(max_length=200, label='제목')
    your_content = forms.CharField(widget=forms.Textarea, label='내용')
    your_star = forms.ChoiceField(widget = forms.Select(), choices = ([('1','★'), ('2','★★'),('3','★★★'), ('4','★★★★'), ('5','★★★★★')]), initial='1', label='별점 선택', required = True)
    your_tag = forms.CharField(max_length=200, label='태그', required=False, widget=forms.TextInput(attrs={'placeholder': 'comma-separated'}))

class NoticeForm(forms.Form):
    your_board = forms.ChoiceField(widget = forms.Select(), choices = ([('1','리뷰 게시판'), ('2','공지사항')]), initial='1', label='게시판 선택', required = True)
    your_title = forms.CharField(max_length=200, label='제목')
    your_content = forms.CharField(widget=forms.Textarea, label='내용')

class BoardManageForm(forms.Form):
    your_boardnum = forms.IntegerField(label='게시판번호')
    your_board = forms.CharField(label='게시판명', max_length=100)

class SearchForm(forms.Form):
    your_search = forms.CharField(max_length=100, label='', widget=forms.TextInput(attrs={'placeholder': 'Enter HashTags..'}))

class SettingForm(forms.Form):
    your_settingnum = forms.IntegerField(label='시간설정')

class FoodForm(forms.Form):
    your_con1 = forms.ChoiceField(widget = forms.Select(), choices = ([('0','갈비만두'), ('1','감자튀김'),('2','떡볶이'), ('3','레몬에이드'), ('4','불닭볶음면'), ('5','소떡소떡'), ('6','수제소시지'), ('7','스프라이트'), ('8','슬라이스 치즈'), ('9','신라면'), ('10','아메리카노'), ('11','자몽에이드'), ('12','제육덮밥'), ('13','짜파게티'), ('14','참치김밥'), ('15','청포도에이드'), ('16','치킨마요덮밥'), ('17','코카콜라'), ('18','펩시'), ('19','포스틱'), ('20','포카칩'), ('21','핫도그'), ('22','핫바'), ('23','햇반'), ('24','허니버터칩'), ('25','홈런볼')]), initial='0', label='메뉴 선택', required = True)

Proj/views.py
from django.views.generic import ListView, FormView
from django.views import View
from Proj.models import *
from taggit.models import *
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse, HttpResponseRedirect
from Proj.forms import *
import json
import hashlib
from django.db.models import Q
import joblib
import pandas as pd


class Login(FormView):
    form_class = LoginForm
    template_name ="Proj/login.html"

    def get(self,request,*args,**kwargs):
        form = self.form_class(initial= self.initial)
        #request.session['login'] = False # 추가 session
        return render(request,self.template_name,{'form':form})

    def post(self,request,*args,**kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_id = form.cleaned_data['your_id']
            new_pw = form.cleaned_data['your_pw']
            m = hashlib.sha256()
            m.update(new_pw.encode('UTF-8'))
            x = m.hexdigest()
            
            try:
                 data = User.objects.get(my_id=new_id)
            except Exception:
                return redirect('proj:login')

            if x == data.pw:
                request.session['login'] = True # 추가 로그인 성공시 True 설정
                request.session['my_id'] = data.my_id
                request.session['time'] = data.time
                request.session['name'] = data.name

                return redirect('proj:main')
            else:
                return redirect('proj:login')
        
        return render(request,self.template_name,{'form':form})
    

class Main(View):

    def get(self, request, *args, **kwargs):
        #if not request.session.get('login', False):
        #    return HttpResponseRedirect('/')
        
        userdata = request.session.get('my_id')
        context = {'model_list':['Board'], 'userdata':userdata}

        return render(request, 'Proj/main.html', context=context)

class Join(FormView):
    form_class = JoinForm
    template_name ="Proj/join.html"

    def get(self,request,*args,**kwargs):
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

    def post(self,request,*args,**kwargs):                  #my_id, pw, name, number, prof
        form = self.form_class(request.POST)
        if form.is_valid():
            new_id = form.cleaned_data['your_id']
            new_pw = form.cleaned_data['your_pw']
            new_ph = form.cleaned_data['your_ph']
            new_name = form.cleaned_data['your_name']
            new_sex = form.cleaned_data['your_sex']
            new_age = form.cleaned_data['your_age']
            new_avg_time = form.cleaned_data['your_avg_time']
            new_food_choice = form.cleaned_data['your_food_choice']
            m = hashlib.sha256()
            m.update(new_pw.encode('UTF-8'))
            x = m.hexdigest()
            try:
                User.objects.create(my_id=new_id, pw=x, name=new_name, ph=new_ph, sex = new_sex, region = 6., avg_time = new_avg_time, food_choice=new_food_choice, age=new_age)
            except:
                return redirect('proj:join')
            request.session['login'] = False
            return HttpResponseRedirect('/')
        
        return render(request,self.template_name,{'form':form})


class Edit(FormView):
    form_class = EditForm
    template_name = 'Proj/edit.html'

    def get(self,request,*args,**kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        new_my_id = request.session.get('my_id')
        form = self.form_class(initial= {'your_id':new_my_id})

        return render(request,self.template_name,{'form':form, 'my_id':new_my_id}) #, 'new_id':new_id
    
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_my_id = request.session.get('my_id')
            new_pw = form.cleaned_data['your_pw']
            new_ph = form.cleaned_data['your_ph']
            new_name = form.cleaned_data['your_name']
            try:
                data = User.objects.get(my_id=new_my_id)
            except Exception:
                return HttpResponse(Exception)

            m = hashlib.sha256()
            m.update(new_pw.encode('UTF-8'))
            x = m.hexdigest()
            if new_name != data.name or new_ph != data.ph or x != data.pw:
                data.pw=x
                data.ph=new_ph
                data.name=new_name
                data.save()
                return HttpResponseRedirect('/')
            else:
                return HttpResponseRedirect('/edit/')
        request.session['login'] = False

        return render(request,self.template_name,{'form':form})        


class Logout(View):

    def get(self, request, *args, **kwargs):
        request.session['login'] = False
        request.session['my_id'] = {}
        request.session['name'] = {}
        request.session['time'] = {}
        return HttpResponseRedirect('/')


class Admin(FormView):
    form_class = AdminForm
    template_name = 'Proj/admin.html'

    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_id = form.cleaned_data['your_id']
            new_prof = form.cleaned_data['your_prof']
            try:
                post_instance = User.objects.filter(my_id=new_id)
                post_instance.update(prof=new_prof)
            except Exception:
                return render(request, 'Proj/admin.html', {'form':form})

            return HttpResponseRedirect('/admin/')

        return render(request, 'Proj/admin.html', {'form':form})

class Maps(View):
    
    def get(self, request, name):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        pcname = name
        return render(request, 'Proj/maps.html', {'name':pcname})           

class Setting(FormView):
    form_class = SettingForm
    template_name = 'Proj/main.html'
    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = SettingForm
        return render(request, 'Proj/setting.html' ,{'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)    
        if form.is_valid():
            new_boardnum = form.cleaned_data['your_settingnum']
            time = new_boardnum
            return render(request, self.template_name ,{'form':form})

class Distance(View):
    
    def get(self, request):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        
        return render(request, 'Proj/distance.html')  

class Boarding(View):
    
    def get(self, request):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')

        val = request.session.get('my_id')
        userdata = User.objects.get(my_id = val)
        boarddata1 = Board.objects.all()

        return render(request, 'proj/board.html', {'userdata':userdata, 'boarddata':boarddata1})


class BoardManage(FormView):
    form_class = BoardManageForm
    template_name = 'Proj/boardmanage.html'
    
    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_boardnum = form.cleaned_data['your_boardnum']
            new_board = form.cleaned_data['your_board']
            Board.objects.create(boardnum=new_boardnum, title=new_board)                

        return redirect('proj:main')

class ContentList(View):

    def get(self, request, boardnum):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')

        data = Text.objects.filter(boardnumber=boardnum).order_by('-id')
        form = SearchForm
        bn = boardnum
        return render(request, 'proj/contentlist.html', {'data':data, 'bn':bn, 'form':form})

    def post(self, request, boardnum):
    
        data = Text.objects.filter(boardnumber=boardnum).order_by('-star')
        bn = boardnum
        form = SearchForm
        return render(request, 'proj/contentlist.html', {'data':data, 'bn':bn, 'form':form})


class SearchContent(FormView):
    form_class = SearchForm
    template_name = 'Proj/contentlist.html'
    
    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

    def post(self, request, boardnum):
        form = self.form_class(request.POST)
        if form.is_valid():
            new_search = form.cleaned_data['your_search']
            data = Text.objects.filter(boardnumber=boardnum).filter(tags__name=new_search)
            bn = boardnum
            return render(request, 'Proj/contentlist.html', {'data':data, 'bn':bn, 'form':form})

        return redirect('proj:main')


class Food(FormView):
    form_class = FoodForm
    template_name = 'Proj/food.html'

    def get(self, request, *args, **kwargs):
        if not request.session.get('login', False):
            return HttpResponseRedirect('/')
        form = self.form_class(initial= self.initial)
        return render(request,self.template_name,{'form':form})

Proj/templates/Proj/admin.html
{% extends "Proj/main.html" %}
{% block content %}
<form action="{% url 'proj:admin' %}" method='post'>
    {% csrf_token %}
    <h2>Admin</h2>
    {{ form.as_p }}
    <input type='submit' value='정보수정' />
</form>
{% endblock %}

Proj/templates/Proj/base.html
{% block title %}

<title>Play Pay</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js"></script>

<nav class="navbar  navbar-expand-sm  bg-dark  navbar-dark"> 
  <a class="navbar-brand" href="/"><h2>Play Pay</h2></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    {% if not request.session.login %}
      <li class="nav-item active">
        <a class="nav-link" href={% url 'proj:login' %}>로그인 <span class="sr-only">(current)</span></a>
      </li>
    {% else %}
      <li class="nav-item active">
        <a class="nav-link" href={% url 'proj:logout' %}>로그아웃 <span class="sr-only">(current)</span></a>
      </li>

      <li class="nav-item">
        <a class="nav-link" href={% url 'proj:edit' %}>정보수정</a>
      </li>
    {% endif %}

      <li class="nav-item">
        <a class="nav-link" href={% url 'proj:pclist' %}>PC방 찾기</a>
      </li>

      {% if request.session.name == '관리자' %}

      <li class="nav-item">
        <a class="nav-link" href={% url 'proj:boardmanage' %}>게시판 관리</a>
      </li>
      {% endif %}

      <li class="nav-item">
        <a class="nav-link" href={% url 'proj:food' %}>메뉴 추천</a>
      </li>

<li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          게시판
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href={% url 'proj:contentlist' 1 %}>리뷰 게시판</a>
          <a class="dropdown-item" href={% url 'proj:contentlist' 2 %}>공지사항</a>
        </div>
      </li>

<li class="nav-item dropdown">
        <a class="nav-link disabled" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         설정
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href={% url 'proj:setting' %}>PC시간 설정</a>
        </div>
      </li>



    </ul>
    <form class="form-inline my-2 my-lg-0">
    <font color='white'>
    {% if request.session.name %}
    <a>이름 : {{ request.session.name }} //</a>
    {% else %}
    이름 : None //
    {% endif %}
    {% if request.session.time %}
    <a>잔여시간 : {{ request.session.time }}분</a>
    {% else %}
    <a>잔여시간 : None </a>
    {% endif %}
    </font>
    <a class="nav-link" href={% url 'proj:payment' %} style="color:#FF8868">충전</a>
    <a class="nav-link" href={% url 'proj:refund' %} style="color:#FF8868">환불</a>
    </form>

<head> 
    <meta charset="UTF-8"> 
    <meta name="viewport" 
        content="width=device-width, initial-scale=1.0"> 
      
    <script src= "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.0/jquery.min.js"> 
    </script> 
      
    <style>    
        h1{ 
        color: #32a852; 
        } 
        .mode { 
            float:left; 
        } 
        .change { 
            cursor: pointer; 
            border: 1px solid #555; 
            border-radius: 40%; 
            width: 20px; 
            text-align: center; 
            padding: 5px; 
            margin-rights: 8px; 
        } 
        .dark{ 
            background-color: #222; 
            color: #ffffff; 
        } 
    </style> 
</head> 
 <style>
  ap{
    color: #ffffff;
  }
 </style> 
<body> 
    <div class="mode"> 
        <ap>Dark mode: </ap><span class="change">🌓</span> 
    </div> 
        
    <script> 
        $( ".change" ).on("click", function() { 
            if( $( "body" ).hasClass( "dark" )) { 
                $( "body" ).removeClass( "dark" ); 
            } else { 
                $( "body" ).addClass( "dark" ); 
            } 
        }); 
    </script> 
</body> 
</nav>


<!-- Channel Plugin Scripts -->
<script>
  (function() {
    var w = window;
    if (w.ChannelIO) {
      return (window.console.error || window.console.log || function(){})('ChannelIO script included twice.');
    }
    var d = window.document;
    var ch = function() {
      ch.c(arguments);
    };
    ch.q = [];
    ch.c = function(args) {
      ch.q.push(args);
    };
    w.ChannelIO = ch;
    function l() {
      if (w.ChannelIOInitialized) {
        return;
      }
      w.ChannelIOInitialized = true;
      var s = document.createElement('script');
      s.type = 'text/javascript';
      s.async = true;
      s.src = 'https://cdn.channel.io/plugin/ch-plugin-web.js';
      s.charset = 'UTF-8';
      var x = document.getElementsByTagName('script')[0];
      x.parentNode.insertBefore(s, x);
    }
    if (document.readyState === 'complete') {
      l();
    } else if (window.attachEvent) {
      window.attachEvent('onload', l);
    } else {
      window.addEventListener('DOMContentLoaded', l, false);
      window.addEventListener('load', l, false);
    }
  })();
  ChannelIO('boot', {
    "pluginKey": "8badb9d9-3049-487c-b0e3-c919c17c281b"
  });
</script>
<!-- End Channel Plugin -->

<style>

<style tyle="text/css">
#wrapper {
	position:relative;

  min-height:100%;
}
#footer {

    position:fixed;

    bottom:0;

    width:100%;

    height:150px;   

    background-color:#525864;

}

#color {color: #ffffffaa;}




</style>


<div id="wrapper">
    <div id="footer"><pre>
    
    <div id="color">
                                                              <b>팀 명</b> 사과파이     <b>팀장</b> 유승현     <b>팀원</b> 이상훈
                                                              <b>주소</b> 충청북도 충주시 대소원면 대학로 50(한국교통대학교) 중앙정보관      TEL 010-1234-5678
                                                              COPYRIGHT 2020. APPLEPIE. ALL RIGHTS RESERVED.</div>
    </pre></div>

</div>



{% endblock %}

{% block content %}
{% endblock %}

Proj/templates/Proj/board.html
{% extends "Proj/main.html" %}
{% block content %}
<h2>Board List</h2>
<!--
{% if object_list %}
    <ul>
    {% for board in object_list %}
        <li><a href="{% url 'proj:contentlist' board.boardnum %}">{{ board.title }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No Board Messages !!!</p>
{% endif %}
-->
{% for board in boarddata %}
    <li><a href="{% url 'proj:contentlist' board.boardnum %}">{{ board.title }}</a></li>
{% endfor %}

{% endblock %}

Proj/templates/Proj/boardmanage.html
{% extends "Proj/main.html" %}
{% block content %}
<style>
#login .container #login-row #login-column #login-box {
  margin-top: 140px;
  max-width: 600px;
  height: 260px;
  border: 1px solid #9C9C9C;
  background-color: #EAEAEA;
}
#login .container #login-row #login-column #login-box #login-form {
  padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
  margin-top: -85px;
}
</style>

<form action="{% url 'proj:boardmanage' %}" method='post'>
    {% csrf_token %}
        <div id="login">
 <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post" style="text-align:center"><br>
                            <h3 class="text-center text-info">게시판 관리</h3>
                            <form action="{% url 'proj:boardmanage' %}" method='post' >
                                {% csrf_token %}<br>

                                {% for field in form %}
                                <div class="form-group">
                                    <input type="{{field.field.widget.input_type}}" class="form-control" id="{{field.id_for_label}}" 
                                        placeholder="{{field.label}}" name="{{field.name}}">
                                </div>
                            {% endfor %}  
                                <input type='submit' class='btn btn-warning' value='게시판 생성' />
                            </form>
                        </form>
                    </div>
                </div>
            </div>
        </div>
 </div>
                        
</form>
{% endblock %}

Proj/templates/Proj/choose.html
{% extends "Proj/main.html" %}
{% block content %}
<form action="{% url 'proj:choose' %}" method='post'>
    {% csrf_token %}
    <h2>회원가입</h2>
    {{ form.as_p }}
    <input type='submit' value='회원가입' />
</form>
<a href="" onclick="window.open('/maps/skybridge/', 'window popup', 'width=500, height=500, menubar=no, status=no, toolbar=no');">테스트하기</a>
{% endblock %}

Proj/templates/Proj/edit.html
{% extends "Proj/base.html" %}
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% block content %}
<style>
#login .container #login-row #login-column #login-box {
  margin-top: 120px;
  max-width: 600px;
  height: 360px;
  border: 1px solid #9C9C9C;
  background-color: #EAEAEA;
}
#login .container #login-row #login-column #login-box #login-form {
  padding: 20px;
}
#login .container #login-row #login-column #login-box #login-form #register-link {
  margin-top: -85px;
}
p{
    color: #000000;
}
</style>
<body>
    <div id="login">
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post" style="text-align:center">
                            <h3 class="text-center text-info">Edit</h3>
                            <form action="{% url 'proj:edit' %}" method='post' >
                                {% csrf_token %}<br>
                                <p>USER_ID : {{ my_id }}</p>
                                    {% for field in form %}
                                <div class="form-group">
                                    <input type="{{field.field.widget.input_type}}" class="form-control" id="{{field.id_for_label}}" 
                                        placeholder="{{field.label}}" name="{{field.name}}">
                                </div>
                            {% endfor %}  
                                <input type='submit' class='btn btn-warning' value='정보수정' />
                            </form>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
{% endblock %}

Proj/templates/Proj/setting.html
{% extends "Proj/main.html" %}
{% block content %}
<h3>

<form action="{% url 'proj:setting' %}" method='post'>
    {% csrf_token %}
    <h2>PC 시간 설정</h2>
    {{ form.as_p }}
    <input type='submit' value='시간 설정' />
</form>

{% endblock %}

<!--darkmode-->


{% if request.session.time <= time %}
<!DOCTYPE html>
<html>
<head>
  <title></title>

  <link rel="stylesheet" type="text/css" href="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
</head>
<body>
  <script type="text/javascript" src="http://code.jquery.com/jquery-3.3.1.min.js"></script>
  <script type="text/javascript" src="http://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
  <div id="myMoney"></div>
  <script>
      jQuery(document).ready(function(){
        $('#myMoney').show();
    });
    {
      toastr.options.escapeHtml = true;
      toastr.options.closeButton = true;
      toastr.options.newestOnTop = false;
      toastr.options.progressBar = true;
      toastr.info('PC방 이용시간이 부족합니다', '충전 알림', {timeOut: 10000});
    };
  
  </script>
</body>
</html>
{% endif %}